[package]
name = "janus_aggregator_api"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
base64 = "0.21.0"
janus_aggregator_core.workspace = true
janus_core.workspace = true
janus_messages.workspace = true
opentelemetry = "0.18"
querystring = "1.1.0"
rand = { version = "0.8", features = ["min_const_gen"] }
ring = "0.16.20"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tracing = "0.1.37"
trillium = "0.2.6"
trillium-api = { version = "0.2.0-rc.2", default-features = false }
trillium-opentelemetry = "0.0.1"
trillium-router = "0.3.5"
trillium-tracing = "0.1.0"
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
futures = "0.3.26"
janus_aggregator_core = { workspace = true, features = ["test-util"] }
tokio = "1.25"
trillium-testing = { version = "0.4.1", features = ["tokio"] }
